# Generated by Django 4.1.5 on 2023-03-12 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=100, verbose_name='Title')),
                ('about_description', models.TextField(max_length=255, verbose_name='Description')),
                ('about_img', models.ImageField(upload_to='img/about/', verbose_name='Image')),
                ('status', models.BooleanField(default=True, help_text='0=inactive, 1=active')),
            ],
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('password', models.CharField(default='pbkdf2_sha256$390000$CokesJWJY7MICaGRR6BaJq$VbyaUkQxcG4KPFRloblGJGc05XV7ugjZRNn/4dTl4mg=', max_length=128, verbose_name='Password')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='Address')),
                ('phone_number', models.CharField(max_length=100, verbose_name='Phone Number')),
                ('esewa_number', models.CharField(max_length=100, null=True, verbose_name='Esewa Number')),
                ('role', models.IntegerField(default=1, help_text='0=business user(owner), 1=admin, 2=sub business user(owner)', verbose_name='User Role')),
                ('status', models.BooleanField(default=True, help_text='0=inactive, 1=active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(verbose_name='Updated Date')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyImg', models.ImageField(upload_to='img/')),
                ('title', models.CharField(max_length=150)),
                ('desc', models.TextField()),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
                ('status', models.BooleanField(default=True, help_text='0=inactive, 1=active')),
            ],
        ),
        migrations.CreateModel(
            name='Counts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_number', models.PositiveIntegerField(verbose_name='Count Number')),
                ('count_title', models.CharField(max_length=50, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=100, verbose_name='Title')),
                ('event_description', models.TextField(verbose_name='Description')),
                ('event_date', models.DateTimeField(verbose_name='Date')),
                ('event_img', models.ImageField(upload_to='img/event/', verbose_name='Image')),
                ('slug', models.SlugField(verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=5100, verbose_name='Title')),
                ('news_description', models.TextField(verbose_name='Description')),
                ('news_author', models.CharField(max_length=50, verbose_name='Written By')),
                ('news_date', models.DateTimeField(verbose_name='News date')),
                ('news_img', models.ImageField(upload_to='img/news/', verbose_name='Image')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicesImg', models.ImageField(upload_to='img/services')),
                ('title', models.CharField(max_length=150)),
                ('desc', models.TextField()),
                ('status', models.BooleanField(default=True, help_text='0=inactive, 1=active')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_title', models.CharField(max_length=100, verbose_name='Title')),
                ('slider_description', models.TextField(max_length=255, verbose_name='Description')),
                ('slider_img', models.ImageField(upload_to='img/slider/', verbose_name='Image')),
                ('status', models.BooleanField(default=True, help_text='0=inactive, 1=active')),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('sub_desc', models.TextField()),
                ('img', models.ImageField(upload_to='img/teams')),
                ('name', models.CharField(max_length=60)),
                ('post', models.CharField(max_length=100)),
                ('fb_link', models.CharField(max_length=150)),
                ('twitter_link', models.CharField(max_length=150)),
                ('insta_link', models.CharField(max_length=150)),
                ('status', models.BooleanField(default=True, help_text='0=inactive, 1=active')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testmoni_name', models.CharField(max_length=50, verbose_name='Name')),
                ('testmoni_designation', models.CharField(max_length=30, verbose_name='Designation')),
                ('testmoni_message', models.TextField(verbose_name='Message')),
                ('status', models.BooleanField(default=True, help_text='0=inactive, 1=active')),
            ],
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('img', models.ImageField(upload_to='img/')),
                ('desc', models.TextField()),
                ('status', models.BooleanField(default=True, help_text='0=inactive, 1=active')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img/galleries')),
                ('top_title', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.adminuser')),
            ],
        ),
    ]
