# Generated by Django 4.1.7 on 2023-03-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyImg', models.ImageField(upload_to='img/')),
                ('title', models.CharField(max_length=150)),
                ('desc', models.TextField()),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
                ('status', models.BooleanField(default=True, help_text='0=inactive, 1=active')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicesImg', models.ImageField(upload_to='img/services')),
                ('title', models.CharField(max_length=150)),
                ('desc', models.TextField()),
                ('status', models.BooleanField(default=True, help_text='0=inactive, 1=active')),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('sub_desc', models.TextField()),
                ('img', models.ImageField(upload_to='img/teams')),
                ('name', models.CharField(max_length=255)),
                ('post', models.CharField(max_length=255)),
                ('fb_link', models.CharField(max_length=255)),
                ('twitter_link', models.CharField(max_length=255)),
                ('insta_link', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True, help_text='0=inactive, 1=active')),
            ],
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('img', models.ImageField(upload_to='img/')),
                ('desc', models.TextField()),
                ('status', models.BooleanField(default=True, help_text='0=inactive, 1=active')),
            ],
        ),
    ]
