# <<<<<<< HEAD
# Generated by Django 4.1.5 on 2023-03-09 09:58
# =======
# Generated by Django 4.1.7 on 2023-03-09 10:04
# >>>>>>> 793310bd1f0d96b55746a1acafc371b9fb67b222

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=50, verbose_name='Title')),
                ('about_description', models.TextField(max_length=500, verbose_name='Description')),
                ('about_img', models.ImageField(upload_to='img/about/', verbose_name='Image')),
=======
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyImg', models.ImageField(upload_to='img/')),
                ('title', models.CharField(max_length=150)),
                ('desc', models.TextField()),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
>>>>>>> 793310bd1f0d96b55746a1acafc371b9fb67b222
                ('status', models.BooleanField(default=True, help_text='0=inactive, 1=active')),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='Counts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_number', models.PositiveIntegerField(verbose_name='Count Number')),
                ('count_title', models.CharField(max_length=50, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=50, verbose_name='Title')),
                ('event_description', models.TextField(verbose_name='Description')),
                ('event_date', models.DateTimeField(verbose_name='Date')),
                ('event_img', models.ImageField(upload_to='img/event/', verbose_name='Image')),
                ('slug', models.SlugField(verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=50, verbose_name='Title')),
                ('news_description', models.TextField(verbose_name='Description')),
                ('news_author', models.CharField(max_length=50, verbose_name='Written By')),
                ('news_date', models.DateTimeField(verbose_name='News date')),
                ('news_img', models.ImageField(upload_to='img/news/', verbose_name='Image')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_title', models.CharField(max_length=50, verbose_name='Title')),
                ('slider_description', models.TextField(max_length=255, verbose_name='Description')),
                ('slider_img', models.ImageField(upload_to='img/slider/', verbose_name='Image')),
=======
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicesImg', models.ImageField(upload_to='img/services')),
                ('title', models.CharField(max_length=150)),
                ('desc', models.TextField()),
>>>>>>> 793310bd1f0d96b55746a1acafc371b9fb67b222
                ('status', models.BooleanField(default=True, help_text='0=inactive, 1=active')),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testmoni_name', models.CharField(max_length=50, verbose_name='Name')),
                ('testmoni_designation', models.CharField(max_length=30, verbose_name='Designation')),
                ('testmoni_message', models.TextField(verbose_name='Message')),
=======
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('sub_desc', models.TextField()),
                ('img', models.ImageField(upload_to='img/teams')),
                ('name', models.CharField(max_length=255)),
                ('post', models.CharField(max_length=255)),
                ('fb_link', models.CharField(max_length=255)),
                ('twitter_link', models.CharField(max_length=255)),
                ('insta_link', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True, help_text='0=inactive, 1=active')),
            ],
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('img', models.ImageField(upload_to='img/')),
                ('desc', models.TextField()),
>>>>>>> 793310bd1f0d96b55746a1acafc371b9fb67b222
                ('status', models.BooleanField(default=True, help_text='0=inactive, 1=active')),
            ],
        ),
    ]
