# Generated by Django 4.1.7 on 2023-03-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$AOIRMinrgbR2xZkJ78O3O3$YoCVZgRhGuQ4o94EuROM+BkotJaxNRp7fl2hB19dSpo=', max_length=128, verbose_name='Password'),
        ),
    ]
