# Generated by Django 4.1.5 on 2023-03-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blog_eventdetails_faq_newsdetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$mooRelBG7k8sorbo6D4Y6s$gDCPnRJ5g4sgR4870jLxyHKnx70JfaE4fbXx2vcjqpw=', max_length=128, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='event_date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_date',
            field=models.DateField(verbose_name='News date'),
        ),
        migrations.AlterField(
            model_name='newsdetails',
            name='news_date',
            field=models.DateField(verbose_name='News date'),
        ),
    ]
