# Generated by Django 4.1.7 on 2023-03-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_adminuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$5CbKetFcPSWcQw05BDDOZu$PbSeUpCoJJfwyjwvjaQGj6eFsuOP5/P4VNpdaT6wK7g=', max_length=128, verbose_name='Password'),
        ),
    ]
