# Generated by Django 4.1.5 on 2023-03-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_adminuser_password_alter_event_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$Q9BmEW4zatT03WCDPJqw4R$zVi+JwmzuLkKf6fOWotc+0d578P4YQH8QZfIhC34vVg=', max_length=128, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='event_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='event_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='event_img',
            field=models.ImageField(upload_to='img/event/'),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='event_title',
            field=models.CharField(max_length=100),
        ),
    ]
