# Generated by Django 4.1.7 on 2023-03-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_adminuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$gInMI7X33leXyRDI9Hfam9$vyjKAZngH4aHfKvZb9MlNTb0HqLrAFFpanqkes8mgP0=', max_length=128, verbose_name='Password'),
        ),
    ]
