# Generated by Django 4.1.7 on 2023-03-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_adminuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$j8AfPOjp2QK2oBIRNxvKPn$sPKTE5pi+b5DoglIbvPlMmWR+w94req6JXe5UoqY6fc=', max_length=128, verbose_name='Password'),
        ),
    ]
