# Generated by Django 4.1.5 on 2023-03-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_adminuser_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$kV6TDymNdKV6rfaWVrVjcN$Se1gVZJLkwDweGZaTUWoePQsUSNVN3S2m62O8zOzEtU=', max_length=128, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='event_date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='event_img',
            field=models.ImageField(upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='event_title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='slug',
            field=models.CharField(max_length=100, verbose_name=''),
        ),
    ]
