# Generated by Django 4.1.5 on 2023-03-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_adminuser_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=100, verbose_name='Title')),
                ('about_description', models.TextField(max_length=255, verbose_name='Description')),
                ('about_img', models.ImageField(upload_to='img/about/', verbose_name='Image')),
                ('status', models.BooleanField(default=True, help_text='0=inactive, 1=active')),
            ],
        ),
        migrations.CreateModel(
            name='blogDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img/blogImg/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=200)),
                ('author_img', models.ImageField(upload_to='img/authorImg/')),
                ('slug', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TestimonialDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testmoni_name', models.CharField(max_length=50, verbose_name='Name')),
                ('testmoni_designation', models.CharField(max_length=30, verbose_name='Designation')),
                ('testmoni_message', models.TextField(verbose_name='Message')),
                ('status', models.BooleanField(default=True, help_text='0=inactive, 1=active')),
            ],
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$6jzdPi5ebWTd31ePA2vGx0$qsTOSoEZfvkJNGhcYMPXegGknq7YGjEZxo99Wub5xKs=', max_length=128, verbose_name='Password'),
        ),
    ]
