# Generated by Django 4.1.7 on 2023-03-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_adminuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$3FN4jGgL9ufLcBgDDHaLV6$6ca2rtNRCt2Du+PYxdEAUDshlyliGmJaA9w+HNOpTIw=', max_length=128, verbose_name='Password'),
        ),
    ]
