# Generated by Django 4.1.7 on 2023-03-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_adminuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$p4XKOoPtD7584cAG68Muk5$6g25y0coRElw7rAu1CfnHyEUmCkc6Jsz/4i63qsrdkE=', max_length=128, verbose_name='Password'),
        ),
    ]
