# Generated by Django 4.1.5 on 2023-03-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_aboutdetails_blogdetails_testimonialdetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$39qLAvIcA9puFhoHFrze6D$gSjNfiJf+YIlEOaVs5DwXbrM/GSEM9HJILkt5RrNkOg=', max_length=128, verbose_name='Password'),
        ),
    ]
