# Generated by Django 4.1.7 on 2023-03-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_adminuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$Nz8FTOhhCxnXX4WOfnSHw6$noIpyHuhRZoDmjhXYQ+uxMEe8EYJLcbn1UHVemxfRr8=', max_length=128, verbose_name='Password'),
        ),
    ]
