# Generated by Django 4.1.5 on 2023-03-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_adminuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$ZOhgHbudsj7ltxPbajOEoh$Rd6SPMHNpiD50tkpy3ERr9SXMuUJoMnAP4Q61R3kIYM=', max_length=128, verbose_name='Password'),
        ),
    ]
