# Generated by Django 4.1.7 on 2023-03-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_adminuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$BxzGtkFkHE0Ja1W6eDz3vd$CQrZKwd8cPlzKfZYDJgqRcXokjcgPVPlNzuVJG9Q8KU=', max_length=128, verbose_name='Password'),
        ),
    ]
