# Generated by Django 4.1.7 on 2023-03-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_adminuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$YsEF9EICDVIU2Wwuzt42Jw$ZIceklVOFdCJKjzDeBjSG4QtkJ8hy+CqT7x6tepndew=', max_length=128, verbose_name='Password'),
        ),
    ]
