# Generated by Django 4.1.7 on 2023-03-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_adminuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$erAKUwmR8tAve1sPmYbWoZ$8bKNzlkrFSh6ItX0ywnB9thVFkDlMxorAEczrd7Is94=', max_length=128, verbose_name='Password'),
        ),
    ]
