# Generated by Django 4.1.5 on 2023-03-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_user_alter_gallery_user_id_delete_adminuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$03PPsYCx1pt4f4BOyAgeKP$yB9PWsd1OTAkof9ECRSxDEehPPiRE73XM8nI9uJmm14=', max_length=128, verbose_name='Password'),
        ),
    ]
