# Generated by Django 4.1.7 on 2023-03-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$JpDiOd4LSLcs35hXQpuhBB$NMIp1zk0DT8zCuBBrRltGhrWo4yGDGDpcHBxlwthbb4=', max_length=128, verbose_name='Password'),
        ),
    ]
