# Generated by Django 4.1.7 on 2023-03-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_adminuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$2rv6K7U579ZJYWhQoxNBaP$yp0ZDbitsdPPNRjAs+ABxni+3QH44jAXUeXFXOf/UPA=', max_length=128, verbose_name='Password'),
        ),
    ]
