# Generated by Django 4.1.7 on 2023-03-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$Y1ZYCj29INvvRtWGlryrxT$aZN5GBWYMtw0EvgXn9NYM1+5j3m0d0mL5akUnSsTbYI=', max_length=128, verbose_name='Password'),
        ),
    ]
