# Generated by Django 4.1.5 on 2023-03-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$r9plX9LeJSwbACroHb5Cwv$CmCDN0oM2ik95cR+/LnUfskTPOvP3w9OIeEbZ21vFJo=', max_length=128, verbose_name='Password'),
        ),
    ]
