# Generated by Django 4.1.7 on 2023-03-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_adminuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$VQxD84LeUbkXjLzMsgM883$Ewlx9bIjIgNIBfDpt7fE8bhzUtvvL3idSMwYnybGu5Y=', max_length=128, verbose_name='Password'),
        ),
    ]
