# Generated by Django 4.1.7 on 2023-03-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_company_status_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.BooleanField(default='True', help_text='0=inactive, 1=active'),
        ),
    ]
