# Generated by Django 4.1 on 2023-03-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_about_about_description_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='testimonial_img',
            field=models.ImageField(null=True, upload_to='img/testimonial'),
        ),
    ]
