# Generated by Django 4.1.7 on 2023-03-12 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_adminuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='address',
            field=models.CharField(max_length=100, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='esewa_number',
            field=models.CharField(max_length=100, null=True, verbose_name='Esewa Number'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$AfVhKll4E08BsOIwVi2I0y$a6xrI+KrgWajrhSZg0C6Pfw3DR77zR6WHwPSR9PXTV8=', max_length=128, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='phone_number',
            field=models.CharField(max_length=100, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_title',
            field=models.CharField(max_length=5100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='fb_link',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='teams',
            name='insta_link',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='teams',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='teams',
            name='post',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teams',
            name='twitter_link',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img/galleries')),
                ('top_title', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.adminuser')),
            ],
        ),
    ]
