# Generated by Django 4.1.7 on 2023-03-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_company_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.BooleanField(default=True, help_text='0=inactive, 1=active'),
        ),
    ]
