# Generated by Django 4.1 on 2023-03-19 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_company_status'),
        ('main', '0018_teammembers_remove_teams_fb_link_remove_teams_img_and_more'),
    ]

    operations = [
    ]
