# Generated by Django 4.1.7 on 2023-03-19 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_news_slug_alter_user_password'),
        ('main', '0019_merge_20230319_1438'),
    ]

    operations = [
    ]
