<<<<<<< HEAD
# Generated by Django 4.1.7 on 2023-03-19 10:57
=======
# Generated by Django 4.1.7 on 2023-03-19 10:09
>>>>>>> a1587cbe1fc1e8de3679fede5bbf15d05ffb3f49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('main', '0020_merge_20230319_1642'),
=======
        ('main', '0020_merge_20230319_1554'),
>>>>>>> a1587cbe1fc1e8de3679fede5bbf15d05ffb3f49
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Password'),
        ),
    ]
