# Generated by Django 4.1.7 on 2023-03-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_faq_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='status',
            field=models.BooleanField(default=False, help_text='0=default, 1-Active'),
        ),
    ]
