# Generated by Django 4.1.7 on 2023-03-20 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_merge_20230319_1642'),
        ('main', '0024_remove_faq_status'),
    ]

    operations = [
    ]
