# Generated by Django 4.1.5 on 2023-03-21 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_candidate_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='img',
            field=models.ImageField(null=True, upload_to='img/business'),
        ),
        migrations.AddField(
            model_name='business',
            name='logo',
            field=models.ImageField(null=True, upload_to='img/business_logo'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.business'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='candidate_desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='candidate_name',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='total_vote',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='candidate_img',
            field=models.ImageField(null=True, upload_to='img/candidate'),
        ),
    ]
