# Generated by Django 4.1.5 on 2023-03-23 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_faq_message_faq_answer_faq_question'),
        ('main', '0027_business_business_desc_business_img_business_logo_and_more'),
    ]

    operations = [
    ]
