# Generated by Django 4.1.5 on 2023-03-23 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_merge_20230323_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidate_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=5)),
                ('transaction_id', models.CharField(max_length=10)),
                ('esewa_status', models.BooleanField(default=True, help_text='0=inactive, 1=active')),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='business_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=5)),
                ('transaction_id', models.CharField(max_length=10)),
                ('esewa_status', models.BooleanField(default=True, help_text='0=inactive, 1=active')),
                ('business_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.business')),
            ],
        ),
    ]
