# Generated by Django 4.1.5 on 2023-03-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_candidate_payment_business_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='pid',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
